### ISSUE TITLE
Compiler-Error on Data Model

### ISSUE THREAD

**Issue by andreas-barthel** [mandarineorg/mandarinets#168]
**[Details]**
Table-Decorator causes a compiler error at startup of the application.

**[Stacktrace]**
```
error: Uncaught TypeError: Cannot read property 'name' of undefined
        var propertyTypeName = propertyType.name;
                                            ^
    at Function.registerColumnDecorator (ormCoreDecoratorProxy.ts:30:45)
    at entityDecorators.ts:30:31
    at DecorateProperty (reflectMetadata.ts:1216:35)
    at Reflect.decorate (reflectMetadata.ts:739:24)
    at __decorate (file:///C:/Users/username/Documents/projects/private/SuperServer/src/main/mandarine/model/db/Bla.ts:3:92)
    at Bla.ts:9:5
```

**[Scenario]**
Added a data model class like described in the official documentation. Database-Table doen't not exist.
Model-Class:
```
import { Table, Id, GeneratedValue, Column } from "https://x.nest.land/MandarineTS@1.5.0/mod.ts";

@Table({ schema: "public" })
export class Bla {
    @Id()
    @GeneratedValue({strategy: "SEQUENCE"})
    @Column()
    private id: number;
}
```

**[Expected behavior]**
No error, but a table called "bla" in the public schema.

**[Screenshots]**
No screenshots....

**[OS]**
Windows 10 Pro 1909

**[Environment]**
 - Mandarine version: 1.5.0
 - Mandarine CLI version 1.1.0
 - Deno version 1.3.2
 - Deno v8 version 8.6.334
 - Deno typescript version 4.0.2

**Comment by andreas-barthel** [comment]
On my Ubuntu-Server the same error occurs:
- Mandarine version 1.5.0
- Mandarine CLI version 1.1.0
- Deno version 1.3.1
- Deno v8 version 8.6.334
- Deno typescript version 3.9.7

**Comment by andreespirela** [comment]
Hello there, yes. This is a very weird error, I can't seem to reproduce it... @andreas-barthel . I'm committing a fix temporary for 2.0.0. 2.0.0 will be tagged real soon, in the meantime, while I find the real fix, the changes in 2.0.0 should do it. I'll keep you posted. Thanks for reporting this

**Comment by andreespirela** [comment]
Would you mind testing this example: @andreas-barthel 

```typescript
import { Table, Id, GeneratedValue, Column, SQLTypes } from "https://deno.land/x/mandarinets@v2.0.0/mod.ts";

@Table({ schema: "public" })
export class Bla {

    @Id()
    @Column({
        type: SQLTypes.BIGINT
    })
    @GeneratedValue({ strategy: "SEQUENCE" })
    private id: number;

}
```

Make sure to point out to `2.0.0` with deno `1.3.2`.

Let me know.

**Comment by andreas-barthel** [comment]
Hi.
Works fine on my local Windows machine and the Ubuntu server. Error is gone and table "bla" is created. Thanks a lot! :)

**Comment by andreespirela** [comment]
Closed as this was reported to be fixed. Tagging “Needs Investigation” fur further references
