### ISSUE TITLE
Incorrect capitalization of entity-properties after fetch

### ISSUE THREAD

**Issue by andreas-barthel** [mandarineorg/mandarinets#179]
**[Details]**
After fetching entities from database, the entities properties doesn't match the class definition of the TypeScript entity class.
I'm using `lowerCamelCase `for properties that are mapped to lowercase column names in database tables. That is good by now.
But after fetch entities from database via `PostgresConnector.query` the lowercase column names are applied to the builded entity via `Object.assign()`.
So if in the entity is a field/property called `peerId`, then it results in a field called `peerid`. Following code doesn't expect that and access to `entity.peerId` results in `undefined`.

**[Expected behavior]**
I expect after fetching an entity from database that all defined properties are setted up with fieldnames defined in the entity class.

**[OS]**
Windows 10 Pro 1909

**[Environment]**
 - Mandarine version: **2.0.1**
 - Deno version **1.3.2**
 - Deno v8 version **8.6.334**
 - Deno typescript version **4.0.2**

**[Additional]**
I know you want to build a new ORM, so you can consider this issue more then a reminder instead of  a bug ;)

**Comment by andreespirela** [comment]
Yes, I can confirm this behavior as a bug. Initially it was thought to be that way, now I do see the need for keeping the same structure the developer has given it. Thanks for reporting it

**Comment by andreespirela** [comment]
This is more complex than I thought, needs investigation, not sure what version we will be releasing this, but should be a minor version. maybe 2.1.1

**Comment by andreespirela** [comment]
I think this can make it to 2.1.2

**Comment by andreespirela** [comment]
Will be fixed in #196

**Comment by andreespirela** [comment]
Closed in #196 . @andreas-barthel I'd like to make a quick note, I think it'll be realistic to expect errors when executing some queries, if this happens please do let us know. I'm not sure what's the downstream impact of the changes I've made, even with unit test & integration tests it will be hard to track down the whole picture, I'd say 80% chances everything goes well, and 20% something breaks. This is expected and we're here to solve when errors come :)
