### ISSUE TITLE
[bug] about properties.json

### ISSUE THREAD

**Issue by higrw123** [mandarineorg/mandarinets#220]
**[Details]**
properties.json  created by mandarine-cli  exist at src/resources/ , but framework still find at src/main/resources., 

**[Stacktrace]**
[MandarineCompiler.class] properties.json could not be found or parsed. Using default values.

**[Scenario]**
1) mandarine n
2) mandarine r
3) create src/main/resources/properties.json
4) should be ok

**[Expected behavior]**
framework should find properties.json at src/resources/

**[OS]**
E.g. Ubuntu 18.04

**[Environment]**
 - Mandarine version: [e.g. **v2.1.3**]
 - Deno version [e.g. **1.4.6**]

**Comment by higrw123** [comment]
ok, can  avoid this problem by use mandarine.json [propertiesFilePath] to define  the path

**Comment by andreespirela** [comment]
I'm interested in this, @higrw123 what happened exactly, Mandarine was complaining about not finding it in `src/main/resources/properties.json` ?
