### ISSUE TITLE
Add mongodb support

### ISSUE THREAD

**Issue by webpreneur** [mandarineorg/mandarinets#244]
Please implement mongodb support.

**Comment by andreespirela** [comment]
Sure we want to do this. But just to clarify...

What you are asking is MongoDB support in [Mandarine's ORM](https://www.mandarinets.org/docs/master/mandarine/data-interaction) which works along with [MQL (Mandarine Query Language)](https://www.mandarinets.org/docs/master/mandarine/mandarine-query-language) or how exactly are you thinking of a built-in support for MongoDB?

@webpreneur

**Comment by andreespirela** [comment]
Let's land it in 3.0.0

**Comment by webpreneur** [comment]
awesome

**Comment by webpreneur** [comment]
> 
> 
> Let's land it in 3.0.0

awesome

**Comment by andreespirela** [comment]
Closed in https://github.com/mandarineorg/mandarinets/pull/265
