### ISSUE TITLE
Any plan to support OpenAPI

### ISSUE THREAD

**Issue by linux-china** [mandarineorg/mandarinets#250]
Now Mandarinets has annotations for HTTP routing, and any plan to add OpenAPI related annotations to generate OpenAPI json?  It will be friendly for OpenAPI related tools, such as Swagger-UI,  OpenAPI client tools etc.   Now I can not find Deno framework to support OpenAPI. 

* SpringFox: http://springfox.github.io/springfox/docs/current/
* SpringDoc:  https://springdoc.org/

**Comment by andreespirela** [comment]
I'll have to look into it, seems like a nice feature to have. I'll be investigating how we could or could not make this possible.

**Comment by linux-china** [comment]
I created a demo to show use OpenAPI annotations in Mandarine, and the url is https://github.com/linux-china/mandarine-demo

**Comment by andreespirela** [comment]
@linux-china what would be the benefit of using such annotations ? Just general metadata for the application and the developer?

**Comment by linux-china** [comment]
yes, These annotations help to  generate OpenAPI metadata json for the application, otherwise you should write OpenAPI json by hand.   The OpenAPI metadata json is useful for GUI display as document and language SDK generation to call HTTP REST API.

**Comment by andreespirela** [comment]
I like it. Let's land it in 2.4.0
