### ISSUE TITLE
Database connection could not be reached

### ISSUE THREAD

**Issue by Saverio-Angelicola** [mandarineorg/mandarinets#283]
**[Details]**
hello, I have a bug when I want to connect with postgresql because after following the doc and putting my database information I receive as an error: 
[ERROR | 04/20/2021, 2:39:13 PM] [6320] [PostgresConnector.class] Database connection could not be reached.
However, the information in my database is correct.

**[Scenario]**
1) I created the mandarin.json file and insert the path to my properties.json file.
![image](https://user-images.githubusercontent.com/59100393/115398885-e5367200-a1e7-11eb-93ba-13a1d0998e84.png)

2) I entered this json data in properties.json:
![image](https://user-images.githubusercontent.com/59100393/115398053-08145680-a1e7-11eb-8c17-fe1da3888431.png)

3) I then used the command: mandarine run --allow-all --watch

**[Expected behavior]**
Normally I should be able to connect to the DB and be able to use MandarineTS ORM with my DB..

**[Screenshots]**
![image](https://user-images.githubusercontent.com/59100393/115398529-896be900-a1e7-11eb-8c9d-dbc384c06fab.png)

**[OS]**
Windows 10 Pro 64 bits

**[Environment]**
 - Mandarine version: [2.3.2]
 - Deno version [1.9]

**Comment by andreespirela** [comment]
This is a tricky one since we are not showing an stacktrace of the error, when we should. I would suspect your postgres has a different authentication method than the ones supported..

@Saverio-Angelicola I will create a branch for this bug with a debug logger for the DB connection, and you could use that branch instead of `deno.land/x` just to get more information in the meantime. Would that work for you?

**Comment by Saverio-Angelicola** [comment]
Yes, it's good.

**Comment by andreespirela** [comment]
@Saverio-Angelicola This is the branch `github-283` , this is the mod.ts: https://raw.githubusercontent.com/mandarineorg/mandarinets/github-283/mod.ts

any other file you need from the repo, please use it from there.

In order to enable debug logs, please use `DEBUG` environment variable.
Ex.
```
DEBUG=true deno run myscript.ts
```

**Comment by Saverio-Angelicola** [comment]
Here is the error I have now after using the mod.ts: https://raw.githubusercontent.com/mandarineorg/mandarinets/github-283/mod.ts.

![image](https://user-images.githubusercontent.com/59100393/115409008-a5748800-a1f1-11eb-9226-3236016c8506.png)

**Comment by andreespirela** [comment]
Try again, remember to use the flag `--reload` so Deno fetches the module again @Saverio-Angelicola

**Comment by Saverio-Angelicola** [comment]
It still doesn't work even with the flag --reload.

![image](https://user-images.githubusercontent.com/59100393/115413012-21240400-a1f5-11eb-9c9f-c65bb94690b1.png)

**Comment by Saverio-Angelicola** [comment]
I still have the same bug there are no differences.

![image](https://user-images.githubusercontent.com/59100393/115420005-18363100-a1fb-11eb-929b-887969aaafcd.png)

**Comment by andreespirela** [comment]
@Saverio-Angelicola Are you still getting the one with `this[msgType] is not a function`, or that one went away?

**Comment by Saverio-Angelicola** [comment]
This error is no longer there but restarting the server without the --watch flag I have this error:

![image](https://user-images.githubusercontent.com/59100393/115420678-a0b4d180-a1fb-11eb-9efd-09d93c506b9c.png)

**Comment by andreespirela** [comment]
Ok that's perfect. 

cc @soremwar . @Saverio-Angelicola is getting an unknown auth message code *10. Would you know what this is about? Thanks

**Comment by andreespirela** [comment]
@Saverio-Angelicola Further discussion with @Soremwar , seems like authentication method number 10 is not supported but it is in latest versions, I will be submitting a patch version throughout the day and that should solve the issue.

**Comment by Saverio-Angelicola** [comment]
OK thank you for your answer.

**Comment by andreespirela** [comment]
@Saverio-Angelicola After further investigation, The latest version of Postgres used by Mandarine is only compatible with Deno 1.9.0, deno 1.9.0 breaks many of our tests (already solved in master branch) but will not be able to create a release since it will be unstable. Best is to way for Mandarine v3.0.0. We apologize for this inconvenience, Mandarine v3.0.0 will be available soon.

**Comment by Saverio-Angelicola** [comment]
Hello, the connection to my postgres database now works without problem with the url: "https://raw.githubusercontent.com/mandarineorg/mandarinets/github-283/mod.ts",
that you gave me for the mod.ts compared to last time.
