### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by buttercubz** [mandarineorg/mandarinets#75]
I read your post on dev.to and saw that you are looking for collaborators so I think that my team and I could help you, we are the developers of [Trex](https://github.com/crewdevio/Trex) package manager.

**Comment by andreespirela** [comment]
Great. Do you have any Discord channel/Discord user where we can talk more in details?

Best.

**Comment by buttercubz** [comment]
my discord username is buttercubz#7085
