### ISSUE TITLE
Unsupported compiler options: allowUmdGlobalAccess

### ISSUE THREAD

**Issue by ebebbington** [mandarineorg/mandarinets#86]
**[Details]**
When running an app with `allowUmdGlobalaccess` inside the `tsconfig.json` (as notes in the docs), i get a warning that it is't supported, and ignores it anyway:
```typescript
// tsconfig.json
{
  "compilerOptions": {
    "strict": false,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "alwaysStrict": false,
    "strictNullChecks": false,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowUmdGlobalAccess": false
  }
}
```

This doesn't break anything

**[Stacktrace]**
Edwards-MacBook-Pro:benchmarks edwardbebbington$ deno run -A --config tsconfig.json mandarinets.ts 
Check file:///mandarinets.ts
Unsupported compiler options in "/tsconfig.json"
  The following options were ignored:
    allowUmdGlobalAccess

**[Scenario]**
1) Create a basic mandarinets file:
```typescript
// app.ts
import { Controller, GET, MandarineCore } from "https://deno.land/x/mandarinets/mod.ts";

@Controller()
export class MyController {

  @GET('/')
  public helloWorld() {
    return `Hello World!`;
  }

}

new MandarineCore().MVC().run();

console.log("Server started")
```
2) Create the tsconfig:
```
{
  "compilerOptions": {
    "strict": false,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "alwaysStrict": false,
    "strictNullChecks": false,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowUmdGlobalAccess": false
  }
}
```

3) Run the server:
```
$ deno run -A --config tsconfig.json app.ts
```

**[Expected behavior]**
Works as expected, just seems like that config makes no difference?

**[OS]**
N/A

**[Environment]**
 - Mandarine version: **v1.2.1**
 - Deno version :**1.2.0**
 - Deno v8 version: **v8 8.5.216**
 - Deno typescript version: **3.9.2**

**Comment by andreespirela** [comment]
Hey there, thanks for reporting this.
Yes, I’ve looked into this. It seems like Deno 1.2.0 stopped supporting that property in the tsconfig... We’ll update the tsconfig really soon, we should be updating it along with the guidelines before releasing Mandarine’s official website, let’s say, one week from now.

I will close this as this is something more documentation-related than bug-related. Further questions or issues, please feel free to open one.
