### ISSUE TITLE
Add integration test for nest.land

### ISSUE THREAD

**Issue by andreespirela** [mandarineorg/mandarinets#98]
Mandarine must have an integration test that confirms Mandarine's latest nest.land module is fully stable. This integration test must run in a different workflow.

**Comment by t8** [comment]
What do you mean by determining stability of the module? If you are referring to it being "online," this would be quite easy to do 👍

**Comment by andreespirela** [comment]
> What do you mean by determining stability of the module? If you are referring to it being "online," this would be quite easy to do 👍

Yes so we basically want to verify the latest release of nest.land is stable and all the imports are missing, we don't do this with deno.land/x because deno.land/x fetches the github repository, so we can assure that it has all the imports working properly. But in nest.land since files are sent through a transaction to a blockchain, we want to verify that all the files passed the transaction and are working properly. If you look here https://github.com/mandarineorg/mandarinets/tree/master/tests/integration-tests/files , we have all those integrations tests pointing out to the same repository, now Mandarine needs a integration test (a single file) with all the most important components of Mandarine, but instead of pointing out to the project's folder, we point out to `https://x.nest.land/MandarineTS@1.2.3/mod.ts` 
so like 
```
import { Controller, GET, MandarineCore, Injectable, Service .... bla bla bla } from "https://x.nest.land/MandarineTS@1.2.3/mod.ts" 
```

**Comment by t8** [comment]
Fair enough. Thanks for the explanation. That really wouldn't be too difficult to do, as you'd just need to ensure that no errors occur when you attempt to import the function(s).

**Comment by andreespirela** [comment]
Closing this issue as I have to re-think whether I want to do this
